name: develop

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: create deployment
        id: create_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments
          repository: ${{ github.repository }}
          ref: ${{ steps.extract_branch.outputs.branch }}
          required_contexts: |
            []
          environment: develop
        env:
          GITHUB_TOKEN: "${{ secrets.MY_GITHUB_TOKEN }}"
